use_frameworks!
platform :ios, '11.0'

target 'AmbrosusViewer' do
  pod 'AmbrosusSDK', :path => '../'
end


target 'AmbrosusBlockchainSDKTests' do
    pod 'AmbrosusBlockchainSDK', :path => '../'
    pod 'web3swift.pod', :git => 'https://github.com/bankex/web3swift.git', :branch => 'master', :modular_headers => true
end
